### ISSUE TITLE
podman run: lines are terminated with CRLF

### ISSUE THREAD

**Issue by edsantiago** [projectatomic/libpod#373]
`podman run` emits lines to stdout terminated with CRLF (\r\n) instead of the conventional LF (\n):

    # podman run --name foo registry.access.redhat.com/rhel7/rhel:latest cat /etc/adjtime |cat -e
    0.0 0 0.0^M$
                0^M$
                    UTC^M$
                          # podman logs foo | cat -e
    0.0 0 0.0$
    0$
    UTC$                  

`podman logs` does not exhibit the same behavior.

I can't figure out where this is originating. Sorry.

**Comment by mheon** [comment]
Putting money on this being conmon

**Comment by mheon** [comment]
Huh. I might have to eat my words. No \r\n in the code over there.

**Comment by rhatdan** [comment]
@nalind PTAL
I think we have the same issue with buildah which does not use conmon.

**Comment by rhatdan** [comment]
@mrunalp PTAL

**Comment by baude** [comment]
@edsantiago I think this is fixed...can you confirm?

**Comment by edsantiago** [comment]
@baude do you have a build? At first glance it seems to be still present in podman-0.3.5-1.gitdb6bf9e.fc27

**Comment by edsantiago** [comment]
Looks to be fixed in podman-0.4.1-1.gitb51d327.fc27. I'm still seeing a curious behavior in which, at some point in docker-autotest, tty settings get b0rked; in particular, `-echo` and `-opost`. If I track that down, I'll file a new issue.
