### ISSUE TITLE
podman rm --force: unable to get exit code

### ISSUE THREAD

**Issue by edsantiago** [projectatomic/libpod#527]
Synopsis: `podman rm --force` results in error message from container process, and (ISTM) fails to perform full cleanup.

1. In window 1, run `podman run --name foo fedora sleep 60`
1. In window 2, run `podman rm --force foo`. It will take 10 seconds, emit the cid, and exit 0.

Result in window 1:
```
ERRO[0014] unable to get exit code of container 69ef42efc70c2dfbdfdd95dd11764b31ab2522cbe06a40ed8b9a528093e92d34: "error updating container 69ef42efc70c2dfbdfdd95dd11764b31ab2522cbe06a40ed8b9a528093e92d34 state: container 69ef42efc70c2dfbdfdd95dd11764b31ab2522cbe06a40ed8b9a528093e92d34 does not exist in database: no such container"                                                               
container has already been removed                                
# echo $?
125
```
In addition, the stale mount count (`mount|grep /run/netns|wc -l) goes up by one. Many thanks to @mheon for his scrum comments today which got me to start looking at this.

**Comment by mheon** [comment]
This will be solved by the work I'm doing with conmon exit commands, allowing us to have an actual cleanup callback.

**Comment by baude** [comment]
@edsantiago this should now be fixed ... you need a very recent build of conmon

**Comment by mheon** [comment]
@baude No this is not fixed - this is not a conmon issue. This is a timing issue with our cleanup.

**Comment by Vogtinator** [comment]
I can confirm this is not fixed in 1.0.0. Please reopen.

**Comment by mheon** [comment]
We're now tracking this at https://github.com/containers/libpod/issues/1640
