### ISSUE TITLE
Podman is not honoring the --memory run flag

### ISSUE THREAD

**Issue by jwendell** [projectatomic/libpod#940]
/kind bug

It seems podman is not honoring what is passed via --memory flag to run subcomand.
I created a [small C program](https://gist.github.com/jwendell/0e22fb0b18efaf696ba46eca83cc9f0f) that allocates an amount of memory passed via argv[1]. Build it with `cc mem.c -o mem`.

Now let's start podman:
`podman run --rm -it -m 4M --name jw centos:7 bash`

From other terminal, copy `mem` binary to the running container:
`cp /home/jwendell/mem $(podman mount jw)`

Now let's execute `mem` passing as argument an amount higher than 4M:
```
[root@40040cff4c4f /]# /mem 14194304
Allocating 14194304 bytes of memory...
Allocated successfuly 0x7f5165031010
Using that memory...
Success.
Freeing memory...
Success.
```
As you can see, the process ran fine.

Compare it with docker, executing same steps above:
```
[root@d344564ea9af /]# ./mem 14194304
Allocating 14194304 bytes of memory...
Killed
```
So, I'd expect podman to kill the process due to OOM.

**Output of `podman version`:**
```
Version:       0.6.1
Go Version:    go1.10.2
OS/Arch:       linux/amd64
```
**Output of `podman info`:**
```
host:
  MemFree: 10796298240
  MemTotal: 16679841792
  SwapFree: 4293652480
  SwapTotal: 4294963200
  arch: amd64
  cpus: 4
  hostname: jw-laptop
  kernel: 4.16.14-300.fc28.x86_64
  os: linux
  uptime: 28m 14.11s
insecure registries:
  registries: []
registries:
  registries:
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.access.redhat.com
store:
  ContainerStore:
    number: 0
  GraphDriverName: overlay
  GraphOptions:
  - overlay.override_kernel_check=true
  GraphRoot: /var/lib/containers/storage
  GraphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
  ImageStore:
    number: 1
  RunRoot: /var/run/containers/storage
```

**Comment by mheon** [comment]
Our cgroup memory limits do seem to be taking affect (`sudo podman run -t -i --rm --memory 8mb fedora cat /sys/fs/cgroup/memory/memory.limit_in_bytes`). I wonder if this is the kernel lazily allocating the requested memory (though `calloc` should be zeroing the memory...)

**Comment by jwendell** [comment]
Yeah, that was my first thought when I was testing it with `malloc`. Then I switched to `calloc` and also added a fake usage of that pointer through a loop.

**Comment by mheon** [comment]
Can you `cat /sys/fs/cgroup/memory/memory.limit_in_bytes` inside the container and verify that the number looks accurate?

**Comment by jwendell** [comment]
Yeah, it does.

**Comment by mheon** [comment]
Hmmm. Any chance you can pastebin or gist the code for the test executable, so I can see about reproducing locally?

**Comment by mheon** [comment]
Nevermind, I see you already linked it. Oops.

**Comment by mheon** [comment]
After some experimentation with `top`, it seems like the virtual memory in use is uncapped, but the amount of physical memory actually in use is always below the cap set. I still need to verify the expected behavior with Docker

**Comment by mheon** [comment]
I tried with Docker, and I couldn't even get `gcc` installed as `dnf` OOM'd. I think this is pretty clear evidence that, whatever we're doing with memory limits, it does not match what Docker does. Going to investigate further.

**Comment by mheon** [comment]
Alright, it looks like we're setting the memory cgroup correctly, but the memsw (memory + swap total) cgroup is not being set. Docker seems to default it to double the memory limit you set if not explicitly overridden, so we'll go with that.

**Comment by mheon** [comment]
Should be fixed by #946

**Comment by gllera** [comment]
Hello,

I still can't limit the max memory usage of a container in the latest Podman (v2.0.4).

Am I missing something or this issue is not yet done?

Reproduction:
```
# Container execution
sudo podman run --rm -it --memory=100m --memory-swap=100m ubuntu bash

# Inside the container:
root@dcb3319af7f7:/# apt update && apt install stress && stress --vm 4 --vm-bytes 1024M
```

Podman stats:
```
ID            NAME              CPU %    MEM USAGE / LIMIT  MEM %     NET IO             BLOCK IO           PIDS                           
dcb3319af7f7  peaceful_leavitt  335.11%  2.882GB / 104.9MB  2748.38%  107.3kB / 14.53MB  372.2MB / 15.23MB  7
```

\* Notice that the memory limit is exceeded by 2748%

**Comment by gllera** [comment]
It seems to be some kind of bug. If `stress-ng` is used insted of `stress`, the memory limit does work.


Reproduction (using stress-ng):
```
# Container execution
sudo podman run --rm -it --memory=100m --memory-swap=100m ubuntu bash

# Inside the container:
root@190f6234b559:/# apt update && apt install stress-ng && stress-ng --vm 4 --vm-bytes 1024M
```

Podman stats:
```
ID            NAME            CPU %    MEM USAGE / LIMIT  MEM %   NET IO           BLOCK IO          PIDS                                  
190f6234b559  thirsty_colden  392.69%  104.8MB / 104.9MB  99.99%  180kB / 17.31MB  8.301GB / 18.5MB  11
```

**Comment by gllera** [comment]
Maybe the logs from `dmesg` helps: [dmesg.txt](https://github.com/containers/podman/files/5018828/dmesg.txt)

During `stress` it shows constantly a lot of new output but during `stress-ng` it shows nothing new.

My kernel version is:
```
Linux flash 5.7.11-arch1-1 #1 SMP PREEMPT Wed, 29 Jul 2020 21:38:21 +0000 x86_64 GNU/Linux
```

**Comment by rhatdan** [comment]
Please open a new issue.
