### ISSUE TITLE
podman build --quiet: isn't

### ISSUE THREAD

**Issue by edsantiago** [projectatomic/libpod#963]
It's not entirely clear how `--quiet` should work, but I think it needs fine-tuning.
```
# d=$(mktemp -d);printf "FROM fedora\nRUN echo aaa\n" >$d/Dockerfile;podman build --quiet $d
aaa
Getting image source signatures
Skipping fetch of repeat blob sha256:891e1e4ef82ad02a4ea1f030831f942d722c7694c4db64ca3239c8163b811c58
Copying blob sha256:9fd6ca992df007e6b612a7c1bde51ed9e43e27aec215bd1670ebcc0034b51f5c
 120 B / 120 B [============================================================] 0s
Copying config sha256:a30196a2272fd0eacf1e42aa2e9c788e5441e4123f04395540af5b1906b8c4f1
 1.56 KB / 1.56 KB [========================================================] 0s
Writing manifest to image destination
Storing signatures
b0936e13a56fd0203dc103dc1a63d20b852198d44c7e6da656e8e7326f048b77
```
The `aaa` and hash are on stdout; progress indicators on stderr. IMO with `--quiet` the only thing I want to see is the hash on stdout.

**Comment by rhatdan** [comment]
Fixed by #964

**Comment by edsantiago** [comment]
@rhatdan could you please double-check? I'm no longer seeing the progress messages, but still seeing output from RUN commands:
```
# d=$(mktemp -d);printf "FROM fedora\nRUN echo aaa\n" >$d/Dockerfile;podman build --quiet $d
aaa
41c495774056eb4c309fc025a5b59660a00908f666c7d1d58c00c697f62dd5ef
```

**Comment by baude** [comment]
thats a buildah bug ... they are aware of it.

**Comment by pierreprinetti** [comment]
Still prints `--> Using cache y78hcry7382chrxy7380hcyr0834` (on stdout!).

Moreover, does not print an image ID when `build` is run without an explicit `--tag`.

Should this be reported as a Buildah issue?

**Comment by TomSweeneyRedHat** [comment]
@pierreprinetti if you're using 1.6.3 or later of Podman and are seeing this issue, please do raise an error against Buildah [here](https://github.com/containers/buildah/issues).

**Comment by pierreprinetti** [comment]
I have 1.6.2, looks like I have to upgrade. Somehow, I didn't see the change in Podman's CHANGELOG, it's probably in Buildah's then. Thank you!
